import { Link } from "wouter";
import logoPath from "@assets/logo_1773342065527.png";

export default function TermsOfUse() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <header className="flex items-center gap-3 px-6 py-4 border-b border-border">
        <Link href="/" className="flex items-center gap-3 hover:opacity-80 transition-opacity">
          <img src={logoPath} alt="Chess Analysis" className="w-8 h-8 object-contain" />
          <span className="font-bold text-base">Chess Analysis</span>
        </Link>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-12">
        <h1 className="text-3xl font-bold mb-2">Terms of Use</h1>
        <p className="text-sm text-muted-foreground mb-10">Last updated: March 2026</p>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-3">1. Acceptance of Terms</h2>
          <p className="text-muted-foreground leading-relaxed">
            By accessing or using Chess Analysis ("the Service") at chessanalysis.co, you agree to be
            bound by these Terms of Use. If you do not agree to these terms, please do not use the Service.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-3">2. Description of Service</h2>
          <p className="text-muted-foreground leading-relaxed">
            Chess Analysis is an interactive chess analysis tool that combines the Stockfish chess engine
            with large language model (LLM) AI coaching. It allows you to import, play through, and
            analyse chess games with engine evaluations and natural language coaching explanations.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-3">3. Free Tier and Accounts</h2>
          <div className="space-y-3 text-muted-foreground leading-relaxed">
            <p>
              You may use the Service without an account to import up to 5 games. After reaching this
              limit, a Google account sign-in is required to continue importing games.
            </p>
            <p>
              By signing in with Google, you authorise us to access your basic profile information
              (name, email, and profile picture) in accordance with our Privacy Policy. You are
              responsible for maintaining the security of your account.
            </p>
          </div>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-3">4. Acceptable Use</h2>
          <p className="text-muted-foreground mb-3 leading-relaxed">You agree not to:</p>
          <ul className="list-disc list-inside space-y-2 text-muted-foreground leading-relaxed">
            <li>Use the Service for any unlawful purpose</li>
            <li>Attempt to circumvent usage limits or access controls through technical means</li>
            <li>Submit content that is harmful, abusive, or violates the rights of others</li>
            <li>Resell, sublicense, or redistribute access to the Service without permission</li>
            <li>Reverse engineer or attempt to extract the underlying AI models or engine configuration</li>
            <li>Use automated scripts to make excessive requests to the Service</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-3">5. AI-Generated Content</h2>
          <div className="space-y-3 text-muted-foreground leading-relaxed">
            <p>
              The coaching explanations, move analyses, and strategic suggestions provided by the Service
              are generated by AI (OpenAI's language models) and verified against the Stockfish engine.
              While we strive for accuracy, AI-generated content may contain errors or inaccuracies.
            </p>
            <p>
              You should not rely solely on this Service for competitive play decisions. The tagline
              "LLMs fact checked by Stockfish" reflects our intent to ground AI output in engine
              evaluations, but does not constitute a guarantee of correctness.
            </p>
          </div>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-3">6. Intellectual Property</h2>
          <p className="text-muted-foreground leading-relaxed">
            The Chess Analysis name, logo, and interface design are our property. The Stockfish engine
            is open source software licensed under the GNU GPL v3. Chess game notation (PGN) submitted
            by you remains your property. AI-generated coaching text is provided for your personal use
            and may not be republished commercially without permission.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-3">7. Third-Party Services</h2>
          <p className="text-muted-foreground leading-relaxed">
            The Service integrates with Chess.com and Lichess to fetch game data on your behalf, subject
            to their respective terms of service. We are not affiliated with or endorsed by Chess.com,
            Lichess, OpenAI, or Google.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-3">8. Disclaimers and Limitation of Liability</h2>
          <div className="space-y-3 text-muted-foreground leading-relaxed">
            <p>
              The Service is provided "as is" without warranties of any kind, either express or implied.
              We do not warrant that the Service will be uninterrupted, error-free, or that defects will
              be corrected.
            </p>
            <p>
              To the fullest extent permitted by law, we shall not be liable for any indirect, incidental,
              special, consequential, or punitive damages arising from your use of, or inability to use,
              the Service.
            </p>
          </div>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-3">9. Modifications to the Service</h2>
          <p className="text-muted-foreground leading-relaxed">
            We reserve the right to modify, suspend, or discontinue the Service at any time without
            notice. We may also update these Terms of Use from time to time. Continued use of the Service
            after any changes constitutes acceptance of the updated terms.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-3">10. Governing Law</h2>
          <p className="text-muted-foreground leading-relaxed">
            These terms shall be governed by and construed in accordance with applicable law. Any disputes
            arising from these terms or your use of the Service shall be resolved through good-faith
            negotiation before any formal proceedings.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-3">11. Contact</h2>
          <p className="text-muted-foreground leading-relaxed">
            For questions about these terms, please contact us at{" "}
            <a href="mailto:legal@chessanalysis.co" className="text-primary hover:underline">
              legal@chessanalysis.co
            </a>.
          </p>
        </section>
      </main>

      <footer className="border-t border-border px-4 py-1 text-center text-[10px] text-muted-foreground/40">
        <div className="flex flex-wrap items-center justify-center gap-4">
          <Link href="/" className="hover:text-foreground transition-colors">Home</Link>
          <Link href="/privacy" className="hover:text-foreground transition-colors">Privacy Policy</Link>
          <Link href="/about" className="hover:text-foreground transition-colors">About Us</Link>
          <Link href="/contact" className="hover:text-foreground transition-colors">Contact Us</Link>
        </div>
      </footer>
    </div>
  );
}
